### ISSUE TITLE
To_hipscat fails with a catalog where columns has been added

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/lsdb#282] opened 2024-04-19 18:42 UTC
As shown during the monthly hipscat working group meeting, the following sniper fails (last line, when uncommented), probably because of the problems in the metadata.

![dummy](https://github.com/astronomy-commons/lsdb/assets/12860669/8e14dee8-2053-42bb-a512-d88ca1032447)

**Comment by camposandro** [comment] 2024-05-02 21:22
Hi @nevencaplar! I executed this exact snippet on both test data and ZTF and I was not able to reproduce the issue saving the catalog with `to_hipscat`. @smcguire-cmu has access to the `trilegal-flip` catalog used here and, from what I could understand, this workflow worked as expected for him too. Do you have any idea of what the error was about?

**Comment by smcguire-cmu** [comment] 2024-05-02 21:24
It's because this code was executed with the `map_partitions` method defined in the image, which I think doesn't properly update the dask meta and causes issues from that. Our testing used the `map_partitions` that was recently added to LSDB that does update the meta. I think we can close this issue, that using the new `map_partitions`in lsdb fixes things.

**Closed by smcguire-cmu** 2024-05-02 21:24 UTC
Labels: bug
