### ISSUE TITLE
Add tutorial for joining

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/lsdb#417] opened 2024-09-17 17:38 UTC
Currently there is no tutorial for how to perform joins

**Comment by hombit** [comment] 2024-09-17 18:54
Could we make something from this?

https://github.com/lincc-frameworks/notebooks_lf/blob/main/ps1-snad.ipynb

**Comment by delucchi-cmu** [comment] 2024-10-30 17:31
Duplicate of https://github.com/astronomy-commons/lsdb/issues/388

**Closed by delucchi-cmu** 2024-10-30 17:31 UTC
Labels: documentation
