### ISSUE TITLE
Missing jinja2 and dask[diagnostics] packages when running lsdb.read_hipscat()

### ISSUE THREAD

**Issue by stargaser** [astronomy-commons/lsdb#121] opened 2024-01-16 23:29 UTC
I am running a notebook in which I'm using lsdb 0.1 (installed with pip into a Python 3.11.7 conda environment). Upon using `lsdb.read_hipscat()` I get an error `ModuleNotFoundError: No module named 'jinja2'`.

Then the traceback later says

```
The above exception was the direct cause of the following exception:
```

followed by 

```
ImportError: Dask diagnostics requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[diagnostics]" --upgrade  # or python -m pip install
```

Shouldn't a `pip install lsdb` have installed these for me?

**Comment by stargaser** [comment] 2024-01-16 23:33
Later in my notebook I got another error:

```
ImportError: dask.distributed is not installed.

Please either conda or pip install distributed:

  conda install dask distributed             # either conda install
  python -m pip install "dask[distributed]" --upgrade    # or pip install
```

Same question, shouldn't this have been installed automatically?

**Comment by delucchi-cmu** [comment] 2024-01-17 14:59
@hombit has tried to re-create this issue unsuccessfully. Can you please attach the notebook you're working with that causes this issue?

**Comment by stargaser** [comment] 2024-01-17 16:52
I've attached the executed notebook (it's in MyST Markdown format so needs jupytext) and the requirements.txt file as it now stands, with the extra items added in.

Initially I created a conda environment with python=3.11 as detailed in the "Environment Setup" section of the notebook.

[requirements.txt](https://github.com/astronomy-commons/lsdb/files/13966172/requirements.txt)
[CosmoDC2_HiPSCat.md](https://github.com/astronomy-commons/lsdb/files/13966171/CosmoDC2_HiPSCat.md)

**Comment by stargaser** [comment] 2024-01-17 17:01
The catalog accessed by the notebook was generated using hipscat-import v0.1. In a few weeks, @troyraen will regenerate it with hipscat-import v0.2 and then we plan to put it in the cloud.

**Comment by mjuric** [comment] 2024-01-26 16:45
In case it's related, running `pytest` on lsdb with only the runtime requirements triggers the missing `jinja2 error.

```
$PREFIX/lib/python3.11/site-packages/dask/widgets/__init__.py:4:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from __future__ import annotations

    import datetime
    import html
    import os.path

>   from jinja2 import Environment, FileSystemLoader, Template
E   ModuleNotFoundError: No module named 'jinja2'

$PREFIX/lib/python3.11/site-packages/dask/widgets/widgets.py:7: ModuleNotFoundError

The above exception was the direct cause of the following exception:

small_sky_order1_catalog = Dask DataFrame Structure:
                         id       ra      dec ra_error dec_error Norder    Dir   Npix
nparti...    ...      ...      ...      ...       ...    ...    ...    ...
Dask Name: read_parquet_file_to_pandas, 1 graph layer

    def test_catalog_html_repr_equals_ddf_html_repr(small_sky_order1_catalog):
>       assert small_sky_order1_catalog._repr_html_() == small_sky_order1_catalog._ddf._repr_html_()

tests/lsdb/catalog/test_catalog.py:23:
```
That import seems to be coming from `dask.widgets`, which makes me think it's a dask dependency bug (they forgot to require jinja2)?

**Comment by camposandro** [comment] 2024-01-27 00:19
@stargaser, I am having a closer look at this issue to try to figure out its cause but I am having trouble reproducing it from a fresh Python 3.11.7 environment.

I tried `read_hipscat` both from a Python console and a Jupyter notebook (using a kernel on this environment) and loading catalogs was successful. Note that most dependencies on `requirements.txt` were already sub-dependencies of LSDB and hipscat and therefore I didn't specify them explicitly. 
 
If you have some time, could you please create a new environment using the code snippet below? I apologize if you already attempted this but I just want to make sure your environment is unintentionally corrupted.
```
conda create -n lsdb_env python=3.11.7
conda activate lsdb_env
python3 -m pip install lsdb ray ipywidgets
python3 -m ipykernel install --user --name lsdb_env --display-name "lsdb_env"
```

This should install a slightly newer version of LSDB (v0.1.1), which adjusts some of the Dask optional dependencies required. Hopefully, it will resolve your issue. If any of the previous error messages persist, one last thing I'd like you to try is installing the complete Dask version, which includes all dependencies for all collections:
```
python3 -m pip install "dask[complete]"
```
This command should install Jinja2, as well as bokeh (required for spinning up the diagnostics dashboard), which you might be requiring for your workflow.

**Comment by stargaser** [comment] 2024-01-27 00:43
Thanks @camposandro , I tried the steps with an extra `pip install ipykernel` needed to make the last step work:
```
conda create -n lsdb_env python=3.11.7
conda activate lsdb_env
python3 -m pip install lsdb ray ipywidgets
python3 -m ipykernel install --user --name lsdb_env --display-name "lsdb_env"
```
My notebook is running without error.

Maybe that means this issue can be closed?

**Comment by camposandro** [comment] 2024-01-29 16:12
We appreciate your feedback, @stargaser, glad it worked out! I am adding the dependency on `dask[diagnostics]` to ease the process of spinning up the Dask dashboard (for profiling) and it will automatically close this issue.

**Closed** 2024-01-29 16:22 UTC
Labels: question
